In [1]:
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier,LogisticRegression
from sklearn.naive_bayes import MultinomialNB,GaussianNB,ComplementNB,BernoulliNB,CategoricalNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn import metrics
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("whatsapp_chat_labeled.csv")
dataset

,Date,Time,Name,Chat,Label
0,10/14/26,1:47 PM,Nivetha,Good morning,Normal
1,10/14/26,1:47 PM,Nivetha,How are you?,Normal
2,10/14/26,1:49 PM,Kirthi,Hi,Normal
3,10/14/26,1:50 PM,Kirthi,Good..u?,Normal
4,10/14/26,1:50 PM,Nivetha,Fine😊,Normal
...,...,...,...,...,...
144,10/19/26,12:45 PM,Kirthi,"Sure, come over and I'll give you an empty bowl😂",Normal
145,10/19/26,12:45 PM,Nivetha,"Wow, such hospitality! I deserve better from you.",Flirty
146,10/19/26,12:46 PM,Kirthi,May be you do. I'll consider it😜,Flirty
147,10/19/26,12:46 PM,Nivetha,"I'll remember that. Anyway, I need to get back...",Normal
148,10/19/26,12:47 PM,Kirthi,"Okay, talk later. Don't miss me too much😂",Flirty

In [3]:
x=dataset["Chat"]
y=dataset["Label"]

In [4]:
def  count_split(x,y):
    X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=53)
    count_vectorizer = CountVectorizer(stop_words='english')
    count_train = count_vectorizer.fit_transform(X_train)
    count_test = count_vectorizer.transform(X_test)
    len(count_vectorizer.get_feature_names_out())#unique words
    print(count_train.toarray())
    return count_train,count_test,y_train,y_test

In [5]:
def cm_prediction(classifier,X_test,y_test):
    y_pred=classifier.predict(X_test)
    from sklearn.metrics import confusion_matrix
    cm=confusion_matrix(y_test,y_pred)
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import classification_report
    Accuracy=accuracy_score(y_test,y_pred)
    report=classification_report(y_test,y_pred)
    from sklearn.metrics import f1_score
    f1=f1_score(y_test,y_pred,pos_label='Flirty')
    return Accuracy,report,cm,f1

In [6]:
def Multinomial(count_train,y_train,count_test,y_test):
    classifier = MultinomialNB()
    classifier.fit(count_train, y_train)
    pred = classifier.predict(count_test)
    score = metrics.accuracy_score(y_test, pred)
    Accuracy,report,cm,f1=cm_prediction(classifier,count_test,y_test)
    return  classifier,Accuracy,report,cm,f1

In [13]:
def logistic(count_train,y_train,count_test,y_test):
    from sklearn.linear_model import LogisticRegression
    classifier=LogisticRegression(random_state=0,max_iter=1000)
    classifier.fit(count_train,y_train)
    Accuracy,report,cm,f1=cm_prediction(classifier,count_test,y_test)
    return classifier,Accuracy,report,cm,f1

In [15]:
def svm_linear(count_train,y_train,count_test,y_test):
    from sklearn.svm import SVC
    classifier = SVC(kernel = 'linear', random_state = 0)
    classifier.fit(count_train, y_train)
    Accuracy,report,cm,f1=cm_prediction(classifier,count_test,y_test)
    return  classifier,Accuracy,report,cm,f1

In [17]:
def svm_NL(count_train,y_train,count_test,y_test):
    from sklearn.svm import SVC
    classifier = SVC(kernel = 'rbf', random_state = 0)
    classifier.fit(count_train, y_train)
    Accuracy,report,cm,f1=cm_prediction(classifier,count_test,y_test)
    return  classifier,Accuracy,report,cm,f1

In [19]:
def knn(count_train,y_train,count_test,y_test):
    from sklearn.neighbors import KNeighborsClassifier
    classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
    classifier.fit(count_train, y_train)
    Accuracy,report,cm,f1=cm_prediction(classifier,count_test,y_test)
    return classifier,Accuracy,report,cm,f1

In [21]:
def Decision(count_train,y_train,count_test,y_test):
    from sklearn.tree import DecisionTreeClassifier
    classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
    classifier.fit(count_train, y_train)
    Accuracy,report,cm,f1=cm_prediction(classifier,count_test,y_test)
    return classifier,Accuracy,report,cm,f1

In [23]:
def random(count_train,y_train,count_test,y_test):
    from sklearn.ensemble import RandomForestClassifier
    classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
    classifier.fit(count_train, y_train)
    Accuracy,report,cm,f1=cm_prediction(classifier,count_test,y_test)
    return classifier,Accuracy,report,cm,f1

In [25]:
accnav=[]
acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accdes=[]
accrf=[]

count_train, count_test, y_train, y_test = count_split(x,y)
classifier,Accuracy,report,cm,f1=Multinomial(count_train,y_train,count_test,y_test)  
accnav.append(Accuracy)

classifier,Accuracy,report,cm,f1=logistic(count_train,y_train,count_test,y_test)
acclog.append(Accuracy)

classifier,Accuracy,report,cm,f1=svm_linear(count_train,y_train,count_test,y_test)  
accsvml.append(Accuracy)
    
classifier,Accuracy,report,cm,f1=svm_NL(count_train,y_train,count_test,y_test)  
accsvmnl.append(Accuracy)
    
classifier,Accuracy,report,cm,f1=knn(count_train,y_train,count_test,y_test)  
accknn.append(Accuracy)
    
classifier,Accuracy,report,cm,f1=Decision(count_train,y_train,count_test,y_test)  
accdes.append(Accuracy)
    
classifier,Accuracy,report,cm,f1=random(count_train,y_train,count_test,y_test)  
accrf.append(Accuracy)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]

C:\Anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [35]:
def Flirt_Classification(accnav,acclog,accsvml,accsvmnl,accknn,accdes,accrf):
    dataframe=pd.DataFrame(index=['Accuracy'],columns=['Mutinomial','Logistic','SVMl','SVMnl','KNN','Decision','Random'])
    dataframe.loc['Accuracy','Multinomial']=accnav[0]
    dataframe.loc['Accuracy','Logistic']=acclog[0]
    dataframe.loc['Accuracy','SVMl']=accsvml[0]
    dataframe.loc['Accuracy','SVMl']=accsvml[0]
    dataframe.loc['Accuracy','SVMnl']=accsvmnl[0]
    dataframe.loc['Accuracy','KNN']=accknn[0]
    dataframe.loc['Accuracy','Decision']=accdes[0]
    dataframe.loc['Accuracy','Random']=accrf[0]
    return dataframe

In [37]:
result=Flirt_Classification(accnav,acclog,accsvml,accsvmnl,accknn,accdes,accrf)
result

         Mutinomial Logistic  SVMl SVMnl  KNN Decision Random  Multinomial
Accuracy        NaN     0.54  0.52  0.46  0.4      0.5   0.46         0.56

In [39]:
Flirt_Classification(
    accnav, acclog, accsvml, accsvmnl,
    accknn, accdes, accrf
)

         Mutinomial Logistic  SVMl SVMnl  KNN Decision Random  Multinomial
Accuracy        NaN     0.54  0.52  0.46  0.4      0.5   0.46         0.56